### PR TITLE
Should Fix #830

### LINKED ISSUE #830: [BUG] Ngrok is not working.
Hey!! I am using Userland apk with debian system because I had this same issue in termunx. 

When I try to use Ngrok server it gives me this error

Screenshot_20200917-160351

I am using Nokia 3.2
With Android 10.

Everything else is up to date.

### PR DESCRIPTION
**Pull request by Mushinako**
This stores the activated config path and passes the object instead of the `_config_path` into `establish_connection`

### CODE REVIEW

**Review by sTiKyt — APPROVED** [review]
Wonderful, i was so frustrated trying to figure out what i did wrong... xD

**Review by sTiKyt — CHANGES_REQUESTED** [review]
But you gotta pull request into dev branch

**Comment by sTiKyt** [comment]
Just pull request it into dev instead of master and i'll accept it

**Comment by Mushinako** [comment]
Sorry new here. Just changed it to dev, I think this is how it works?

**Comment by sTiKyt** [comment]
Yep, accepting here

**Pull request merged**
