### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sTiKyt**
People been annoying this repository with endless stupid pull requests because they couldn't clone appropriate branch, so I'm making this pull request for their inferior brains to rest

### CODE REVIEW

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 79
- Added 3812
           

Complexity increasing per file
==============================
- venv/lib/python3.8/site-packages/yaml/reader.py  8
- venv/lib/python3.8/site-packages/chardet/chardistribution.py  6
- venv/lib/python3.8/site-packages/idna/intranges.py  5
- venv/lib/python3.8/site-packages/requests/status_codes.py  6
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_add_all_future_builtins.py  1
- venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py  18
- venv/lib/python3.8/site-packages/pip/_internal/operations/freeze.py  25
- venv/lib/python3.8/site-packages/setuptools/command/upload.py  1
- venv/lib/python3.8/site-packages/setuptools/dep_util.py  4
- venv/lib/python3.8/site-packages/setuptools/__init__.py  7
- venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py  13
- venv/lib/python3.8/site-packages/pip/_internal/models/search_scope.py  8
- venv/lib/python3.8/site-packages/pip/_internal/network/xmlrpc.py  3
- venv/lib/python3.8/site-packages/future/backports/email/parser.py  4
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_input.py  2
- venv/lib/python3.8/site-packages/future/backports/email/iterators.py  5
- venv/lib/python3.8/site-packages/pip/_internal/utils/packaging.py  5
- venv/lib/python3.8/site-packages/chardet/sjisprober.py  9
- venv/lib/python3.8/site-packages/urllib3/contrib/securetransport.py  16
- venv/lib/python3.8/site-packages/pyngrok/exception.py  2
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_future_standard_library_urllib.py  1
- venv/lib/python3.8/site-packages/future/backports/http/cookies.py  12
- venv/lib/python3.8/site-packages/pip/_internal/req/req_tracker.py  9
- venv/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py  5
- venv/lib/python3.8/site-packages/setuptools/errors.py  1
- venv/lib/python3.8/site-packages/yaml/parser.py  27
- venv/lib/python3.8/site-packages/urllib3/response.py  16
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_basestring.py  1
- venv/lib/python3.8/site-packages/pkg_resources/__init__.py  21
- venv/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py  8
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_absolute_import.py  9
- venv/lib/python3.8/site-packages/pip/_internal/utils/glibc.py  4
- venv/lib/python3.8/site-packages/yaml/__init__.py  5
- venv/lib/python3.8/site-packages/chardet/enums.py  1
- venv/lib/python3.8/site-packages/pip/_internal/utils/inject_securetransport.py  5
- venv/lib/python3.8/site-packages/future/backports/email/charset.py  7
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_UserDict.py  6
- venv/lib/python3.8/site-packages/pip/_internal/models/target_python.py  5
- venv/lib/python3.8/site-packages/idna/codec.py  10
- venv/lib/python3.8/site-packages/setuptools/command/saveopts.py  5
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py  19
- venv/lib/python3.8/site-packages/pip/_internal/utils/parallel.py  2
- venv/lib/python3.8/site-packages/urllib3/contrib/socks.py  9
- venv/lib/python3.8/site-packages/past/builtins/misc.py  6
- venv/lib/python3.8/site-packages/setuptools/command/install.py  5
- venv/lib/python3.8/site-packages/setuptools/py33compat.py  4
- venv/lib/python3.8/site-packages/pip/_internal/distributions/wheel.py  4
- venv/lib/python3.8/site-packages/yaml/constructor.py  19
- venv/lib/python3.8/site-packages/future/builtins/disabled.py  1
- venv/lib/python3.8/site-packages/pip/_internal/req/__init__.py  12
- venv/lib/python3.8/site-packages/setuptools/command/easy_install.py  30
- venv/lib/python3.8/site-packages/pip/_internal/utils/datetime.py  1
- venv/lib/python3.8/site-packages/future/backports/html/parser.py  36
- venv/lib/python3.8/site-packages/setuptools/command/setopt.py  9
- venv/lib/python3.8/site-packages/future/builtins/newround.py  9
- venv/lib/python3.8/site-packages/setuptools/command/develop.py  7
- venv/lib/python3.8/site-packages/requests/__init__.py  9
- venv/lib/python3.8/site-packages/chardet/euckrprober.py  1
- venv/lib/python3.8/site-packages/pip/_internal/network/utils.py  6
- venv/lib/python3.8/site-packages/future/standard_library/__init__.py  19
- venv/lib/python3.8/site-packages/urllib3/util/timeout.py  8
- venv/lib/python3.8/site-packages/requests/models.py  24
- controllers/terminal_controller.py  2
- venv/lib/python3.8/site-packages/pip/_internal/distributions/__init__.py  3
- venv/lib/python3.8/site-packages/pip/_internal/vcs/git.py  6
- venv/lib/python3.8/site-packages/urllib3/util/queue.py  1
- venv/lib/python3.8/site-packages/chardet/hebrewprober.py  10
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_execfile.py  1
- venv/lib/python3.8/site-packages/urllib3/connection.py  17
- venv/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py  11
- venv/lib/python3.8/site-packages/chardet/mbcsgroupprober.py  1
- venv/lib/python3.8/site-packages/past/types/basestring.py  1
- venv/lib/python3.8/site-packages/setuptools/depends.py  7
- venv/lib/python3.8/site-packages/past/translation/__init__.py  23
- venv/lib/python3.8/site-packages/pip/_internal/models/candidate.py  1
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_unicode_keep_u.py  2
- venv/lib/python3.8/site-packages/urllib3/exceptions.py  2
- venv/lib/python3.8/site-packages/urllib3/packages/backports/makefile.py  15
- venv/lib/python3.8/site-packages/yaml/scanner.py  29
- venv/lib/python3.8/site-packages/pip/_internal/operations/install/wheel.py  17
- venv/lib/python3.8/site-packages/setuptools/unicode_utils.py  5
- venv/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py  34
- venv/lib/python3.8/site-packages/libfuturize/fixer_util.py  17
- venv/lib/python3.8/site-packages/pip/_internal/utils/misc.py  12
- venv/lib/python3.8/site-packages/pip/_internal/models/scheme.py  1
- venv/lib/python3.8/site-packages/setuptools/glob.py  17
- venv/lib/python3.8/site-packages/requests/sessions.py  15
- venv/lib/python3.8/site-packages/setuptools/py27compat.py  5
- venv/lib/python3.8/site-packages/setuptools/command/rotate.py  6
- venv/lib/python3.8/site-packages/urllib3/contrib/_appengine_environ.py  2
- venv/lib/python3.8/site-packages/urllib3/contrib/ntlmpool.py  6
- venv/lib/python3.8/site-packages/pip/_internal/commands/install.py  31
- venv/lib/python3.8/site-packages/urllib3/packages/ssl_match_hostname/_implementation.py  20
- venv/lib/python3.8/site-packages/yaml/dumper.py  1
- venv/lib/python3.8/site-packages/pip/_internal/models/direct_url.py  6
- venv/lib/python3.8/site-packages/requests/utils.py  19
- venv/lib/python3.8/site-packages/future/builtins/misc.py  7
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_print.py  19
- venv/lib/python3.8/site-packages/chardet/charsetprober.py  9
- venv/lib/python3.8/site-packages/future/backports/urllib/robotparser.py  15
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_add_all__future__imports.py  1
- venv/lib/python3.8/site-packages/setuptools/command/bdist_rpm.py  2
- venv/lib/python3.8/site-packages/pip/_internal/models/wheel.py  5
- models/localization_model.py  1
- venv/lib/python3.8/site-packages/pip/_internal/commands/debug.py  7
- venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py  21
- venv/lib/python3.8/site-packages/pip/_internal/utils/virtualenv.py  5
- venv/lib/python3.8/site-packages/setuptools/extern/__init__.py  4
- venv/lib/python3.8/site-packages/libfuturize/main.py  58
- venv/lib/python3.8/site-packages/pip/_internal/models/link.py  5
- venv/lib/python3.8/site-packages/setuptools/command/register.py  1
- venv/lib/python3.8/site-packages/pip/_internal/utils/hashes.py  7
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py  9
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/provider.py  3
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_unicode_literals_import.py  1
- venv/lib/python3.8/site-packages/past/types/olddict.py  1
- venv/lib/python3.8/site-packages/setuptools/dist.py  18
- controllers/ngrok_controller.py  2
- venv/lib/python3.8/site-packages/chardet/latin1prober.py  4
- venv/lib/python3.8/site-packages/pyngrok/conf.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/wheel.py  7
- venv/lib/python3.8/site-packages/urllib3/filepost.py  5
- venv/lib/python3.8/site-packages/pip/_internal/commands/freeze.py  3
- venv/lib/python3.8/site-packages/setuptools/launch.py  1
- venv/lib/python3.8/site-packages/setuptools/archive_util.py  16
- venv/lib/python3.8/site-packages/yaml/error.py  11
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_future_builtins.py  1
- venv/lib/python3.8/site-packages/pip/_internal/models/selection_prefs.py  2
- venv/lib/python3.8/site-packages/yaml/resolver.py  19
- venv/lib/python3.8/site-packages/pip/_internal/commands/show.py  28
- venv/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py  7
- venv/lib/python3.8/site-packages/setuptools/_imp.py  16
- venv/lib/python3.8/site-packages/future/backports/email/mime/message.py  2
- venv/lib/python3.8/site-packages/urllib3/connectionpool.py  29
- controllers/connection_controller.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/direct_url_helpers.py  8
- venv/lib/python3.8/site-packages/chardet/utf8prober.py  8
- venv/lib/python3.8/site-packages/future/backports/email/__init__.py  1
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_add_future_standard_library_import.py  1
- venv/lib/python3.8/site-packages/pip/_internal/cli/spinners.py  7
- venv/lib/python3.8/site-packages/future/backports/test/support.py  13
- venv/lib/python3.8/site-packages/chardet/gb2312prober.py  1
- venv/lib/python3.8/site-packages/requests/cookies.py  9
- venv/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py  10
- venv/lib/python3.8/site-packages/yaml/emitter.py  46
- venv/lib/python3.8/site-packages/future/builtins/newnext.py  5
- venv/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py  1
- venv/lib/python3.8/site-packages/requests/exceptions.py  4
- venv/lib/python3.8/site-packages/pip/_internal/commands/completion.py  3
- venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py  12
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_unpacking.py  7
- venv/lib/python3.8/site-packages/future/builtins/new_min_max.py  13
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_future_standard_library.py  1
- venv/lib/python3.8/site-packages/future/utils/surrogateescape.py  9
- venv/lib/python3.8/site-packages/pip/_internal/cli/parser.py  11
- venv/lib/python3.8/site-packages/chardet/jpcntx.py  9
- venv/lib/python3.8/site-packages/urllib3/__init__.py  1
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_annotations.py  8
- venv/lib/python3.8/site-packages/urllib3/packages/six.py  17
- venv/lib/python3.8/site-packages/future/backports/email/mime/audio.py  3
- venv/lib/python3.8/site-packages/setuptools/windows_support.py  2
- venv/lib/python3.8/site-packages/pip/_internal/distributions/base.py  1
- venv/lib/python3.8/site-packages/requests/structures.py  2
- venv/lib/python3.8/site-packages/future/backports/email/message.py  19
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_order___future__imports.py  1
- venv/lib/python3.8/site-packages/setuptools/command/py36compat.py  7
- venv/lib/python3.8/site-packages/pip/_internal/operations/install/editable_legacy.py  3
- venv/lib/python3.8/site-packages/future/types/newbytes.py  22
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_remove_old__future__imports.py  1
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_metaclass.py  13
- venv/lib/python3.8/site-packages/urllib3/poolmanager.py  14
- venv/lib/python3.8/site-packages/chardet/cli/chardetect.py  5
- venv/lib/python3.8/site-packages/pip/_internal/cli/main.py  4
- venv/lib/python3.8/site-packages/pip/_internal/utils/urls.py  5
- venv/lib/python3.8/site-packages/future/backports/xmlrpc/server.py  18
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_oldstr_wrap.py  3
- venv/lib/python3.8/site-packages/urllib3/contrib/appengine.py  21
- venv/lib/python3.8/site-packages/setuptools/site-patch.py  19
- venv/lib/python3.8/site-packages/pip/_internal/pyproject.py  21
- venv/lib/python3.8/site-packages/setuptools/extension.py  4
- venv/lib/python3.8/site-packages/pip/_internal/vcs/mercurial.py  5
- venv/lib/python3.8/site-packages/pip/_internal/commands/download.py  5
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_features.py  4
- venv/lib/python3.8/site-packages/pip/_internal/locations.py  15
- venv/lib/python3.8/site-packages/certifi/core.py  2
- venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py  13
- venv/lib/python3.8/site-packages/pip/_internal/commands/hash.py  3
- venv/lib/python3.8/site-packages/pip/_internal/network/lazy_wheel.py  5
- venv/lib/python3.8/site-packages/future/backports/email/errors.py  2
- venv/lib/python3.8/site-packages/chardet/euctwprober.py  1
- venv/lib/python3.8/site-packages/future/types/newint.py  16
- venv/lib/python3.8/site-packages/setuptools/command/sdist.py  6
- venv/lib/python3.8/site-packages/pip/_internal/__init__.py  1
- venv/lib/python3.8/site-packages/yaml/nodes.py  1
- venv/lib/python3.8/site-packages/pip/_internal/utils/distutils_args.py  4
- venv/lib/python3.8/site-packages/urllib3/util/request.py  9
- venv/lib/python3.8/site-packages/pip/_internal/wheel_builder.py  11
- venv/lib/python3.8/site-packages/setuptools/command/install_egg_info.py  5
- venv/lib/python3.8/site-packages/pip/_internal/main.py  1
- venv/lib/python3.8/site-packages/yaml/cyaml.py  1
- venv/lib/python3.8/site-packages/requests/help.py  6
- venv/lib/python3.8/site-packages/chardet/universaldetector.py  24
- venv/lib/python3.8/site-packages/setuptools/_deprecation_warning.py  1
- venv/lib/python3.8/site-packages/future/backports/email/_parseaddr.py  34
- venv/lib/python3.8/site-packages/setuptools/lib2to3_ex.py  5
- venv/lib/python3.8/site-packages/future/types/newopen.py  1
- venv/lib/python3.8/site-packages/chardet/cp949prober.py  1
- venv/lib/python3.8/site-packages/chardet/big5prober.py  1
- venv/lib/python3.8/site-packages/pip/_internal/commands/configuration.py  8
- venv/lib/python3.8/site-packages/setuptools/command/build_py.py  11
- venv/lib/python3.8/site-packages/yaml/loader.py  1
- venv/lib/python3.8/site-packages/pip/_internal/vcs/bazaar.py  5
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_add__future__imports_except_unicode_literals.py  1
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_imports.py  2
- venv/lib/python3.8/site-packages/pyngrok/process.py  15
- venv/lib/python3.8/site-packages/setuptools/py31compat.py  2
- venv/lib/python3.8/site-packages/chardet/escprober.py  8
- venv/lib/python3.8/site-packages/pip/_internal/commands/cache.py  5
- venv/lib/python3.8/site-packages/past/utils/__init__.py  3
- controllers/localization_controller.py  3
- venv/lib/python3.8/site-packages/idna/compat.py  1
- venv/lib/python3.8/site-packages/future/types/newmemoryview.py  1
- venv/lib/python3.8/site-packages/libpasteurize/fixes/feature_base.py  2
- venv/lib/python3.8/site-packages/pip/_internal/utils/encoding.py  8
- Defs/ActionManager/Server/server_runner.py  2
- venv/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py  7
- venv/lib/python3.8/site-packages/setuptools/monkey.py  7
- venv/lib/python3.8/site-packages/setuptools/command/upload_docs.py  11
- venv/lib/python3.8/site-packages/future/tests/base.py  17
- venv/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py  14
- venv/lib/python3.8/site-packages/pip/_internal/operations/check.py  11
- venv/lib/python3.8/site-packages/setuptools/command/alias.py  6
- venv/lib/python3.8/site-packages/requests/adapters.py  24
- venv/lib/python3.8/site-packages/future/types/newlist.py  3
- venv/lib/python3.8/site-packages/future/builtins/newsuper.py  15
- venv/lib/python3.8/site-packages/requests/_internal_utils.py  3
- venv/lib/python3.8/site-packages/setuptools/package_index.py  20
- venv/lib/python3.8/site-packages/setuptools/command/bdist_egg.py  15
- venv/lib/python3.8/site-packages/future/types/newstr.py  13
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_throw.py  2
- venv/lib/python3.8/site-packages/chardet/sbcsgroupprober.py  1
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_imports2.py  5
- venv/lib/python3.8/site-packages/future/types/newrange.py  7
- venv/lib/python3.8/site-packages/future/backports/email/mime/text.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/deprecation.py  5
- venv/lib/python3.8/site-packages/future/utils/__init__.py  9
- venv/lib/python3.8/site-packages/setuptools/command/build_ext.py  16
- venv/lib/python3.8/site-packages/pip/_internal/utils/models.py  2
- venv/lib/python3.8/site-packages/future/backports/xmlrpc/client.py  12
- controllers/system_controller.py  2
- venv/lib/python3.8/site-packages/future/backports/email/mime/nonmultipart.py  1
- venv/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py  12
- venv/lib/python3.8/site-packages/future/moves/html/__init__.py  2
- venv/lib/python3.8/site-packages/pip/_internal/utils/appdirs.py  4
- venv/lib/python3.8/site-packages/setuptools/msvc.py  15
- venv/lib/python3.8/site-packages/pip/_internal/build_env.py  13
- venv/lib/python3.8/site-packages/pip/_internal/index/collector.py  14
- venv/lib/python3.8/site-packages/future/backports/http/client.py  26
- views/connection_view.py  1
- venv/lib/python3.8/site-packages/yaml/events.py  4
- venv/lib/python3.8/site-packages/yaml/serializer.py  7
- venv/lib/python3.8/site-packages/future/backports/_markupbase.py  22
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_fullargspec.py  1
- venv/lib/python3.8/site-packages/future/types/__init__.py  6
- venv/lib/python3.8/site-packages/pip/_internal/models/format_control.py  6
- venv/lib/python3.8/site-packages/requests/hooks.py  6
- venv/lib/python3.8/site-packages/urllib3/util/connection.py  8
- venv/lib/python3.8/site-packages/pip/_internal/exceptions.py  4
- venv/lib/python3.8/site-packages/setuptools/sandbox.py  7
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_metaclass.py  17
- venv/lib/python3.8/site-packages/setuptools/ssl_support.py  12
- venv/lib/python3.8/site-packages/urllib3/util/ssl_.py  20
- venv/lib/python3.8/site-packages/future/backports/urllib/parse.py  27
- venv/lib/python3.8/site-packages/urllib3/fields.py  8
- venv/lib/python3.8/site-packages/pip/_internal/commands/__init__.py  2
- venv/lib/python3.8/site-packages/yaml/tokens.py  4
- models/connection_model.py  1
- venv/lib/python3.8/site-packages/setuptools/command/build_clib.py  9
- venv/lib/python3.8/site-packages/future/backports/html/__init__.py  3
- venv/lib/python3.8/site-packages/idna/core.py  23
- venv/lib/python3.8/site-packages/pip/_internal/commands/check.py  8
- venv/lib/python3.8/site-packages/urllib3/util/wait.py  7
- venv/lib/python3.8/site-packages/pip/_internal/utils/pkg_resources.py  2
- venv/lib/python3.8/site-packages/past/builtins/noniterators.py  6
- views/EULA_view.py  1
- venv/lib/python3.8/site-packages/pip/_internal/configuration.py  7
- controllers/EULA_controller.py  3
- venv/lib/python3.8/site-packages/pip/_internal/commands/help.py  4
- venv/lib/python3.8/site-packages/pip/_internal/utils/compatibility_tags.py  6
- venv/lib/python3.8/site-packages/pip/_internal/commands/list.py  11
- venv/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py  17
- venv/lib/python3.8/site-packages/urllib3/contrib/_securetransport/bindings.py  4
- venv/lib/python3.8/site-packages/pip/_internal/network/auth.py  14
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_raise_.py  4
- venv/lib/python3.8/site-packages/setuptools/namespaces.py  4
- venv/lib/python3.8/site-packages/future/backports/email/mime/application.py  2
- venv/lib/python3.8/site-packages/future/backports/misc.py  9
- venv/lib/python3.8/site-packages/pip/_internal/utils/typing.py  1
- venv/lib/python3.8/site-packages/libpasteurize/main.py  37
- venv/lib/python3.8/site-packages/setuptools/command/dist_info.py  1
- venv/lib/python3.8/site-packages/pyngrok/ngrok.py  11
- venv/lib/python3.8/site-packages/pip/_internal/req/constructors.py  20
- venv/lib/python3.8/site-packages/yaml/composer.py  8
- venv/lib/python3.8/site-packages/pip/_internal/network/cache.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/logging.py  8
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_print_with_import.py  1
- venv/lib/python3.8/site-packages/pkg_resources/py31compat.py  4
- venv/lib/python3.8/site-packages/setuptools/command/egg_info.py  23
- venv/lib/python3.8/site-packages/yaml/representer.py  22
- venv/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py  9
- venv/lib/python3.8/site-packages/pip/_internal/cli/command_context.py  3
- venv/lib/python3.8/site-packages/setuptools/build_meta.py  8
- venv/lib/python3.8/site-packages/future/backports/urllib/response.py  3
- Defs/FeatureManager/feature_prompt.py  6
- venv/lib/python3.8/site-packages/pip/_internal/cache.py  9
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/base.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py  27
- venv/lib/python3.8/site-packages/future/backports/http/cookiejar.py  23
- venv/lib/python3.8/site-packages/setuptools/installer.py  20
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_kwargs.py  11
- venv/lib/python3.8/site-packages/pkg_resources/extern/__init__.py  4
- venv/lib/python3.8/site-packages/chardet/eucjpprober.py  9
- venv/lib/python3.8/site-packages/setuptools/py34compat.py  1
- venv/lib/python3.8/site-packages/pip/_internal/models/index.py  1
- venv/lib/python3.8/site-packages/chardet/sbcharsetprober.py  12
- venv/lib/python3.8/site-packages/future/backports/urllib/request.py  23
- venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py  22
- venv/lib/python3.8/site-packages/pip/__init__.py  1
- venv/lib/python3.8/site-packages/setuptools/command/install_lib.py  4
- venv/lib/python3.8/site-packages/pip/_internal/req/req_set.py  21
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_raise.py  13
- venv/lib/python3.8/site-packages/future/types/newobject.py  3
- venv/lib/python3.8/site-packages/chardet/codingstatemachine.py  2
- venv/lib/python3.8/site-packages/pip/_internal/network/download.py  9
- venv/lib/python3.8/site-packages/setuptools/command/install_scripts.py  7
- venv/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py  7
- venv/lib/python3.8/site-packages/urllib3/util/retry.py  21
- venv/lib/python3.8/site-packages/pip/_internal/resolution/base.py  1
- venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py  17
- venv/lib/python3.8/site-packages/urllib3/util/url.py  22
- venv/lib/python3.8/site-packages/setuptools/command/bdist_wininst.py  2
- venv/lib/python3.8/site-packages/future/types/newdict.py  4
- venv/lib/python3.8/site-packages/pip/_internal/network/session.py  19
- venv/lib/python3.8/site-packages/chardet/charsetgroupprober.py  8
- venv/lib/python3.8/site-packages/pip/_internal/utils/filesystem.py  10
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_division_safe.py  7
- venv/lib/python3.8/site-packages/future/backports/total_ordering.py  12
- venv/lib/python3.8/site-packages/setuptools/wheel.py  7
- venv/lib/python3.8/site-packages/pip/_internal/commands/wheel.py  11
- venv/lib/python3.8/site-packages/setuptools/command/test.py  9
- venv/lib/python3.8/site-packages/libpasteurize/fixes/fix_future_builtins.py  1
- venv/lib/python3.8/site-packages/urllib3/request.py  5
- venv/lib/python3.8/site-packages/requests/api.py  2
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/requirements.py  4
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py  11
- venv/lib/python3.8/site-packages/pip/_internal/distributions/installed.py  1
- venv/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py  33
- venv/lib/python3.8/site-packages/urllib3/util/response.py  7
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_cmp.py  1
- venv/lib/python3.8/site-packages/urllib3/contrib/_securetransport/low_level.py  8
- venv/lib/python3.8/site-packages/urllib3/_collections.py  11
- venv/lib/python3.8/site-packages/requests/auth.py  19
- venv/lib/python3.8/site-packages/pyngrok/installer.py  10
- venv/lib/python3.8/site-packages/pip/_internal/utils/setuptools_build.py  9
- venv/lib/python3.8/site-packages/pip/_internal/commands/search.py  15
- venv/lib/python3.8/site-packages/past/types/oldstr.py  3
- venv/lib/python3.8/site-packages/pip/_internal/utils/compat.py  7
- venv/lib/python3.8/site-packages/chardet/mbcharsetprober.py  9
- venv/lib/python3.8/site-packages/setuptools/config.py  9
- venv/lib/python3.8/site-packages/pip/_internal/vcs/subversion.py  15
- venv/lib/python3.8/site-packages/chardet/__init__.py  3
- venv/lib/python3.8/site-packages/libfuturize/fixes/fix_xrange_with_import.py  1
         

Clones added
============
- venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py  2
- venv/lib/python3.8/site-packages/yaml/__init__.py  1
- venv/lib/python3.8/site-packages/chardet/langthaimodel.py  1938
- venv/lib/python3.8/site-packages/future/backports/datetime.py  10
- venv/lib/python3.8/site-packages/setuptools/command/easy_install.py  2
- venv/lib/python3.8/site-packages/chardet/langhungarianmodel.py  516
- venv/lib/python3.8/site-packages/yaml/scanner.py  6
- venv/lib/python3.8/site-packages/chardet/mbcssm.py  3998
- venv/lib/python3.8/site-packages/pip/_internal/commands/install.py  2
- venv/lib/python3.8/site-packages/yaml/dumper.py  11
- venv/lib/python3.8/site-packages/libfuturize/main.py  3
- venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py  5
- venv/lib/python3.8/site-packages/chardet/latin1prober.py  55
- venv/lib/python3.8/site-packages/chardet/langbulgarianmodel.py  974
- venv/lib/python3.8/site-packages/future/backports/test/support.py  2
- venv/lib/python3.8/site-packages/yaml/emitter.py  8
- venv/lib/python3.8/site-packages/chardet/jpcntx.py  1773
- venv/lib/python3.8/site-packages/pip/_internal/commands/download.py  1
- venv/lib/python3.8/site-packages/future/backports/email/_policybase.py  1
- venv/lib/python3.8/site-packages/chardet/langhebrewmodel.py  2305
- venv/lib/python3.8/site-packages/yaml/cyaml.py  11
- venv/lib/python3.8/site-packages/setuptools/command/build_py.py  1
- venv/lib/python3.8/site-packages/yaml/loader.py  2
- venv/lib/python3.8/site-packages/future/backports/email/_header_value_parser.py  6
- venv/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py  2
- venv/lib/python3.8/site-packages/future/types/newstr.py  2
- venv/lib/python3.8/site-packages/setuptools/command/build_ext.py  2
- venv/lib/python3.8/site-packages/setuptools/msvc.py  1
- venv/lib/python3.8/site-packages/chardet/escsm.py  1853
- venv/lib/python3.8/site-packages/future/backports/email/policy.py  1
- venv/lib/python3.8/site-packages/future/backports/urllib/parse.py  2
- venv/lib/python3.8/site-packages/chardet/langcyrillicmodel.py  411
- venv/lib/python3.8/site-packages/libpasteurize/main.py  3
- venv/lib/python3.8/site-packages/chardet/langturkishmodel.py  828
- venv/lib/python3.8/site-packages/pip/_internal/req/constructors.py  2
- venv/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py  1
- venv/lib/python3.8/site-packages/future/backports/http/cookiejar.py  2
- venv/lib/python3.8/site-packages/chardet/langgreekmodel.py  3826
- venv/lib/python3.8/site-packages/pip/_internal/commands/wheel.py  2
- venv/lib/python3.8/site-packages/requests/auth.py  2
- venv/lib/python3.8/site-packages/pip/_internal/vcs/subversion.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=6104787&bid=19983334)

**Review by AdrMXR — APPROVED** [review]

**Comment by lia665** [comment]
how to get license. 
Iam stuck here
Help me

**Review by usama7628674 — APPROVED** [review]

**Comment by usama7628674** [comment]
@sTiKyt LGTM!

**Review by darkmidus — APPROVED** [review]

**Review by graysuit — COMMENTED** [review]
Didn't checked files But I recommend to add detailed how_to_contribute.md where all information and steps should be written. Like fork , do edits and then pull etc. And also make sure to think whether your PR is needed and worthful with correct steps. Incorrect or chunks will be rejected.

**Comment by sTiKyt** [comment]
Done

**Pull request merged**
