### PR TITLE
update ngrokConfig

### PR DESCRIPTION
**Pull request by AdrMXR**

### CODE REVIEW

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=6059279&bid=19847113)

**Comment by AdrMXR** [comment]
This modification allows many not to be left charging when generating the ngrok link

**Comment by sTiKyt** [comment]
It was fixed in dev branch, never modify master branch.

**Comment by AdrMXR** [comment]
> It was fixed in dev branch, never modify master branch.

in the dev branch I see that it remains the same, can I make the pull request for the dev branch?

**Comment by sTiKyt** [comment]
@AdrMXR If you think you understand how it has to be done

**Pull request closed without merging**
