### PR TITLE
Merge Dev to Master

### PR DESCRIPTION
**Pull request by darkmidus**

### CODE REVIEW

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 24
- Added 7
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 39
- Added 38
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 3
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 49
- Added 13
           

Complexity increasing per file
==============================
- Defs/FeatureManager/feature_prompt.py  6
- Defs/ActionManager/Server/server_runner.py  2
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 46
- Added 37
           

Complexity increasing per file
==============================
- Defs/FeatureManager/feature_prompt.py  6
- Defs/ActionManager/Server/server_runner.py  2
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 48
- Added 35
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 49
- Added 44
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
- views/EULA_view.py  1
- controllers/EULA_controller.py  3
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 49
- Added 44
           

Complexity increasing per file
==============================
- views/EULA_view.py  1
- controllers/EULA_controller.py  3
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 47
- Added 46
           

Complexity increasing per file
==============================
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
- controllers/EULA_controller.py  3
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- controllers/EULA_controller.py  3
- Defs/FeatureManager/feature_prompt.py  6
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- Defs/FeatureManager/feature_prompt.py  6
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
- controllers/EULA_controller.py  3
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
- controllers/EULA_controller.py  3
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- Defs/ActionManager/Server/server_runner.py  2
- views/EULA_view.py  1
- controllers/EULA_controller.py  3
- Defs/FeatureManager/feature_prompt.py  6
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- controllers/EULA_controller.py  3
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 51
- Added 49
           

Complexity increasing per file
==============================
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
- controllers/EULA_controller.py  3
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 76
- Added 83
           

Complexity increasing per file
==============================
- Defs/FeatureManager/feature_prompt.py  6
- controllers/EULA_controller.py  3
- views/EULA_view.py  1
- Defs/ActionManager/Server/server_runner.py  2
         

Clones added
============
- Defs/ActionManager/simple_informant.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Comment by r3x07** [comment]
unblock me on telegram

**Comment by sTiKyt** [comment]
@r3x07 you are not blocked, stop off-topic

**Comment by r3x07** [comment]
sorry for off-topic but unblock me from the group

**Comment by sTiKyt** [comment]
It's too early to merge, closing here to get rid of spam in Telegram chat

**Comment by sTiKyt** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 79
- Added 102
           

Complexity increasing per file
==============================
- controllers/EULA_controller.py  3
- views/EULA_view.py  1
- views/connection_view.py  1
- models/localization_model.py  1
- Defs/ActionManager/Server/server_runner.py  2
- Defs/FeatureManager/feature_prompt.py  6
- models/connection_model.py  1
- controllers/localization_controller.py  3
- controllers/connection_controller.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DarkSecDevelopers/HiddenEye/pullRequest?prid=5839119&bid=19117097)

**Pull request closed without merging**
