### PR TITLE
Make Steam looks more like orginal

### PR DESCRIPTION
**Pull request by Bartixxx32**
Before:
screenshot-2019-1-30 steam community
After:
screenshot-2019-1-30 steam community 3
Orginal:
screenshot-2019-1-30 steam community 2

Tested and seems work

### CODE REVIEW

**Comment by sTiKyt** [comment]
@Bartixxx32 Fine,if you want you can learn more about htmp and css at [freeCodeCamp](https://www.freecodecamp.org/)

**Comment by sTiKyt** [comment]
@Bartixxx32 for future pull request i recomend you to use our dev branch

**Comment by Bartixxx32** [comment]
Just make a little fix make button green like org

**Comment by sTiKyt** [comment]
@usama7628674 so, if you ok wtih this pull request, please press "Merge pull request" button
Cause we with @An0nUD4Y approved already :D

**Comment by Bartixxx32** [comment]
Ok will use dev branch but i think its only frontend feature with not needed code changes in script itself then i think there is no way to make somentig crashing etc

**Comment by Bartixxx32** [comment]
I will only tell there is 2 commits one with major changes and one named "Update index.html" to make Sign in button green

**Comment by Bartixxx32** [comment]
Ok thanks for merge :)

**Comment by sTiKyt** [comment]
@Bartixxx32 yep but we just need to become more organized, i also will write documentation and guidelines at future :D
And thank you for your contribution!
I hope you'll contribute again :D

**Comment by Bartixxx32** [comment]
As i see my docker build for image for that app has been started

**Comment by sTiKyt** [comment]
@Bartixxx32 also we have Discord server (at it's very beginning) so, if you want you can join https://discord.gg/kVdr8A

**Pull request merged**
