### PR TITLE
Dependency fixes

### LINKED ISSUE #647: [BUG] AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'
**Describe the bug**
Circular Dependency causing Attribute error. Particularly in the files email_prompt.py and simple_informant.py.
This causes an  AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant', as email_prompt tries to import simple_informant and vice versa.

**To Reproduce**
1. python HiddenEye.py

**Expected behavior**

**Screenshots**
issue

**Device (please complete the following information):**
 - OS: ubuntu 16.04
 - Python: Python 3.6.8
 - HiddenEye Version: Latest from Master

**Additional context**
Traceback:

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/HiddenEye/Defs/ActionManager/main_runner.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/HiddenEye/Defs/ActionManager/simple_informant.py", line 10, in <module>
    import Defs.FeatureManager.EmailManager.email_prompt as email_prompt
  File "/home/HiddenEye/Defs/FeatureManager/EmailManager/email_prompt.py", line 11, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
AttributeError: module 'Defs.ActionManager' has no attribute 'simple_informant'

### PR DESCRIPTION
**Pull request by Souldiv**
fixes #647 

Circular dependency fixes made to the following files:

- Defs/ActionManager/simple_informant.py
- Defs/ActionManager/Server/server_runner.py

deleted: server_menu.py and merged with server_runner.py as the two modules are highly coupled.

The program works, but it is not tested exhaustively.

### CODE REVIEW

**Comment by sTiKyt** [comment]
Also I think you shouldn't merge server_runner.py and server_menu.py because they will be updated later and having those divided makes it easier to organize.

**Comment by sTiKyt** [comment]
Also you failed Codacy quality pass, please fix that too.

**Comment by Souldiv** [comment]
1. Server_Menu contains a single function namely server_selection. The three files (simple_informant.py, server_menu.py, and server_runner.py) are highly coupled which means that they are heavily dependant on each other, separating highly coupled modules will only introduce further problems down the line, I suggest you reconsider the merge as only minor changes are made. The organization of code will only improve unless you would like non-mutual import statements to litter the functions.

2. Yes, there is also a stray import made from LocalizationManager.lang_action_manager.lang_server.lang_server_runner into the 'older' server_menu.py file. will fix that as well, was waiting for a review. 

will work on the requested changes.

**Comment by Souldiv** [comment]
- merged lang_server_menu and lang_server_runner.
- shifted print_as_sorted_menu function from main_runner to LocalizationManager.helper, to reduce unnecessary imports to main_runner.
- fixed codacy quality test. the one that shows up is a pre-existing issue, not introduced in this pull request.

**Comment by Souldiv** [comment]
program works, fixes #627

**Comment by zMaadz** [comment]
**grz@backbox:~/Desktop/HiddenEye$ sudo python3 HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/grz/Desktop/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/grz/Desktop/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok'**

_grz@backbox:~/Desktop/HiddenEye$ sudo python HiddenEye.py
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
ImportError: No module named ActionManager.main_runner_

**Comment by zMaadz** [comment]
grz@backbox:~/Desktop/HiddenEye$ **sudo python HiddenEye.py**
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
   


 import Defs.ActionManager.main_runner as main_runner
ImportError: No module named ActionManager.main_runner

grz@backbox:~/Desktop/HiddenEye$ **sudo python3 HiddenEye.py**
Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/grz/Desktop/HiddenEye/Defs/ActionManager/main_runner.py", line 9, in <module>
    from Defs.ImportManager.unsorted_will_be_replaced import run_command, webpage_set, wait, path, rmtree, pathlib_Path, copyfile, chmod, mkdir, remove
  File "/home/grz/Desktop/HiddenEye/Defs/ImportManager/unsorted_will_be_replaced.py", line 15, in <module>
    from pyngrok import ngrok
ModuleNotFoundError: No module named 'pyngrok

**Comment by Souldiv** [comment]
@zMaadz does this issue pertain to the branch created in this pull request? if not I advise you to use the issues channel.

**Pull request merged**
