### PR TITLE
Fix LocalTunnel Download

### PR DESCRIPTION
**Pull request by Moltivie**

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
Have you tested it as i previously used wget to get these binary localtunnel files.

**Comment by Moltivie** [comment]
Yeah, actually you have imported `requests`, so we just use that instead of importing duplicate modules.

**Comment by An0nUD4Y** [comment]
@Moltivie , 
Getting issues during downloading of files.
And also their is no going on process notification like completion time required or % completed something.
REVERTING CHANGES...
Please Fix It....

**Comment by Moltivie** [comment]
I’ll fix it.

**Pull request merged**
