### PR TITLE
Page updates

### PR DESCRIPTION
**Pull request by darkmidus**
These pages have been updated, I haven't been able to try them yet so I'm not sure it If it works

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
@darkmidus , Can you confirm if the pages are correct or not.

**Comment by darkmidus** [comment]
> @darkmidus , Can you confirm if the pages are correct or not.

I can't try them at the moment as I don't have Linux on this laptop. But I am almost 100% certain they should work. Is there anyway you could try them out to make sure?

**Comment by An0nUD4Y** [comment]
Ok,  then i will add them after testing. 
btw,  Thanks For PR.

**Comment by darkmidus** [comment]
Absolutly no problem, this is chris from telegram btw.

**Comment by An0nUD4Y** [comment]
@darkmidus ..
Please Fix These Issues.
1) Badoo Page is not capturing credentials.
2) Steam Page sign in button not working.

Please Fix these Two issues.
Then only i can merge this PR.
Thank You.

**Comment by An0nUD4Y** [comment]
@darkmidus , BTW Thanks For This PR.

**Comment by darkmidus** [comment]
Thank you. I will get too work on those two pages.

**Comment by darkmidus** [comment]
I believe I fixed steam and badoo pages

**Comment by An0nUD4Y** [comment]
@darkmidus , Everything Looks Good.
I am Merging the PR.
Thanks.

**Pull request merged**
