### PR TITLE
Refactoring Code

### PR DESCRIPTION
**Pull request by Moltivie**
@An0nUD4Y may I have you merge this PL. Cleaned a bit the code.

Thanks.

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
@Moltivie  ,Thanks man.
You just made codes a bit more clean.
I am squashing and merging to master.
Revert Changes anytime if needed.

**Comment by An0nUD4Y** [comment]
And also adding you to admin list.

**Comment by Moltivie** [comment]
@An0nUD4Y you may want to give a new tag here.

Thanks.

**Comment by An0nUD4Y** [comment]
@Moltivie  Now you have the write access ,

**Comment by Moltivie** [comment]
> @Moltivie Now you have the write access ,

Appreciate the permission.

**Comment by An0nUD4Y** [comment]
Are you able to modify codes ...

**Comment by An0nUD4Y** [comment]
Will soon add you to Darksec Admin Team.
Thanks to Support.

**Comment by Moltivie** [comment]
Pleasure for me the contribute. :)

**Comment by Moltivie** [comment]
@An0nUD4Y I may want you to [email me](mailto:moltivie@protonmail.com) anytime you are free to do it.

Thanks.

**Comment by An0nUD4Y** [comment]
I am mostly active on Instagram ..
Check github profile.
Are you a insta User??

**Pull request merged**
