### PR TITLE
Protonmail login panel

### PR DESCRIPTION
**Pull request by deadfishhackers**
[ProtonMail](https://github.com/DarkSecDevelopers/HiddenEye/files/3198835/protonmail.zip)

Here you go and heres a screenshot! <b>It looks a bit sketchy because my pc is 5 years old :p (i realized your script already had it)</b><p>
</p>
<p><b> what it has </b></p>
<ul>
<li>All files need ex: Index.php</li>
<li>Official ProtonMail Phishing Page</li>
</ul>
<hr>
<b>Made with love by </b>
<p align="center"></p>

### CODE REVIEW

**Comment by sTiKyt** [comment]
Also there are lot of conflicts

**Comment by sTiKyt** [comment]
Remove all conflicting files, why you need to apply that much files dude?You don't have to replace them...
Next time just don't commit files that you haven't touched!

**Comment by usama7628674** [comment]
@sTiKyt I'm closing it since it's not close to original protonmail site.

**Comment by sTiKyt** [comment]
ok

**Pull request closed without merging**
