### PR TITLE
Now you can merge this one (Localtunnel)

### PR DESCRIPTION
**Pull request by endbehavi0r**
I re-forked the stuff and added necessary changes.

### CODE REVIEW

**Comment by Moltivie** [comment]
@endbehavi0r may I have you delete the binary option one since it needs some fixing.

You may want to fix it in a second moment.
Thanks.

image

**Comment by endbehavi0r** [comment]
Should I allow checks to download the binary files and store them or remove the whole thing completely?

**Comment by An0nUD4Y** [comment]
Allow checks to download Binary file.

**Comment by endbehavi0r** [comment]
Done

**Comment by An0nUD4Y** [comment]
Made More Changes And Created New Pull Request ..
Also @endbehavi0r is now in Contributors List.
<<<< Thanks For Supporting >>>>>

**Pull request closed without merging**
