### PR TITLE
Improved UI/UX

### PR DESCRIPTION
**Pull request by endbehavi0r**
I implemented getch library to improve the UI/UX through a non buffered input for the educational warning message, end message and email message. It will decrease the hassle of the user to type in the newline for every one character input.

### CODE REVIEW

**Comment by An0nUD4Y** [comment]
@endbehavi0r , i don't know if I should mention it or not.
But getch installation is failing in termux...

**Comment by An0nUD4Y** [comment]
Ok .. 
I have used this to install getch.
' pip3 install py-getch '

**Comment by Moltivie** [comment]
@An0nUD4Y have you checked if it's still not working on Termux?

**Comment by sTiKyt** [comment]
But why does it have to be Termux compatible? You know what?IT doesn't have to be compatible cause it isn't Termux branch... Dont overcomplicate things

**Comment by sTiKyt** [comment]
[CodeFactor](https://www.codefactor.io/repository/github/darksecdevelopers/hiddeneye) found an issue: Unnecessary semicolon

It's currently on:
[Defs\Actions.py:476
](https://github.com/DarkSecDevelopers/HiddenEye/blob/94aa9f7f087590ff568139d3084fd5a0b287a3a6/Defs/Actions.py#L476)Commit 94aa9f7f087590ff568139d3084fd5a0b287a3a6

**Comment by Moltivie** [comment]
You know what, this is even worthless it does not even improve something on the project if you think about it. Secondly it’s better if we do not talk about what is on what branch cause everything is mixed up: some codes should not be on a branch and viceversa.

**Comment by An0nUD4Y** [comment]
This PR is unnecessary ..
The reasons are below.
1) Not improving anything.
2) Increasing the Requirements by adding getch module.
3) it will also increase difficulties to manage the termux branch support (& upcoming branches for support)
4) Will create compatibility issues later (as getch module is not compatible in all Linux distro)


& Still No response From @endbehavi0r

Closing Here , Create New PR if Required.

**Pull request closed without merging**
